<?php

/**
 * @file
 * Module file.
 */

declare(strict_types=1);

use Drupal\content_moderation\Entity\ContentModerationState;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\osu_editorial_workflow\Hook\OsuEditorialWorkflowContentModerationHooks;
use Drupal\osu_editorial_workflow\Hook\OsuEditorialWorkflowEntityBundleHooks;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
#[LegacyHook]
function osu_editorial_workflow_content_moderation_state_insert(ContentModerationState $entity): void {
  Drupal::service(OsuEditorialWorkflowContentModerationHooks::class)->onModerationStateChange($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
#[LegacyHook]
function osu_editorial_workflow_content_moderation_state_update(ContentModerationState $entity): void {
  Drupal::service(OsuEditorialWorkflowContentModerationHooks::class)->onModerationStateChange($entity);
}

/**
 * Implements hook_entity_bundle_create().
 */
#[LegacyHook]
function osu_editorial_workflow_entity_bundle_create($entity_type_id, $bundle) {
  Drupal::service(OsuEditorialWorkflowEntityBundleHooks::class)->entityBundleCreate($entity_type_id, $bundle);
}
