<?php

/**
 * @file
 * Module file.
 */

use Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\content_moderation\Entity\ContentModerationState;
use Drupal\osu_editorial_workflow\Event\ContentModerationEvents;
use Drupal\osu_editorial_workflow\Event\ContentModerationStateChangedEvent;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function osu_editorial_workflow_content_moderation_state_insert(ContentModerationState $entity): void {
  _osu_editorial_workflow_content_moderation_state_helper($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function osu_editorial_workflow_content_moderation_state_update(ContentModerationState $entity): void {
  _osu_editorial_workflow_content_moderation_state_helper($entity);
}

/**
 * Handles content moderation state changes for editorial workflows.
 *
 * This helper method processes changes in moderation states for entities
 * and dispatches the appropriate events when relevant. It ensures support
 * for Drupal's content moderation and custom plugins during state changes.
 * When https://www.drupal.org/i/2873287 is merged, this method will be
 * deprecated and replaced by the core event system.
 *
 * @param \Drupal\content_moderation\Entity\ContentModerationState $entity
 *   The content moderation state entity containing the changes. It includes
 *   moderation state information, workflow details, and associated entity
 *   data to determine whether moderation-related actions should occur.
 *
 * @return void
 *   This method does not return a value but performs internal dispatch of
 *   moderation state change events and logs errors when encountered
 *   (e.g., invalid plugin definitions or missing configurations).
 */
function _osu_editorial_workflow_content_moderation_state_helper(ContentModerationState $entity): void {
  if (class_exists('\Drupal\content_moderation\Event\ContentModerationStateChangedEvent')) {
    // When drupal.org/i/2873287 is merged, Core will dispatch these events.
    return;
  }
  if (class_exists('Drupal\workbench_email\EventSubscriber\ContentModerationStateChangedEvent')) {
    return;
  }
  $entity_type_id = $entity->get('content_entity_type_id')->getString();
  $language_code = $entity->get('langcode')->getString();
  try {
    /** @var \Drupal\Core\Entity\RevisionableStorageInterface $entity_storage */
    $entity_storage = Drupal::entityTypeManager()->getStorage($entity_type_id);
    $moderation_state_storage = Drupal::entityTypeManager()
      ->getStorage($entity->getEntityTypeId());
  }
  catch (InvalidPluginDefinitionException | PluginNotFoundException $exception) {
    \Drupal::logger('osu_editorial_workflow')->error($exception->getMessage());
    return;
  }
  /** @var \Drupal\Core\Entity\RevisionableStorageInterface $moderated_entity */
  $moderated_entity = $entity_storage->loadRevision($entity->get('content_entity_revision_id')
    ->getString());

  /** @var \Drupal\content_moderation\ModerationInformationInterface $moderationInfo */
  $moderationInfo = Drupal::service('content_moderation.moderation_information');
  $isModerated = $moderationInfo->isModeratedEntity($moderated_entity);
  if (!$isModerated) {
    return;
  }
  if ($entity->getLoadedRevisionId() === NULL) {
    $original_state = FALSE;
  }
  else {
    /** @var \Drupal\content_moderation\Entity\ContentModerationState $original_content_moderation_state */
    $original_content_moderation_state = $moderation_state_storage->loadRevision($entity->getLoadedRevisionId());
    if (!$entity->isDefaultTranslation() && $original_content_moderation_state->hasTranslation($language_code)) {
      $original_content_moderation_state = $original_content_moderation_state->getTranslation($language_code);
    }
    $original_state = $original_content_moderation_state->get('moderation_state')
      ->getString();
  }
  $new_state = $entity->get('moderation_state')->getString();
  if ($original_state === $new_state) {
    return;
  }
  $workflow = $entity->get('workflow')->getString();
  \Drupal::service('event_dispatcher')
    ->dispatch(new ContentModerationStateChangedEvent($moderated_entity, $new_state, $original_state, $workflow), ContentModerationEvents::STATE_CHANGED);
}
