<?php

/**
 * @file
 * Installs the accessibility remediation email field.
 */

/**
 * Implements hook_install().
 */
function osu_a11y_remediation_install(): void {
  // Add preserve state to moderation states.
  $workflow_storage = \Drupal::entityTypeManager()
    ->getStorage('workflow');
  $workflows = $workflow_storage->loadByProperties(['id' => 'editorial']);
  /** @var \Drupal\workflows\Entity\Workflow $workflow */
  $workflow = $workflows ? array_values($workflows)[0] : NULL;
  $type_plugin = $workflow->getTypePlugin();
  $type_plugin->addState('preserve', 'Preserved');
  // Get the configuration and set published and default revision flags.
  $configuration = $type_plugin->getConfiguration();
  $configuration['states']['preserve']['published'] = TRUE;
  $configuration['states']['preserve']['default_revision'] = TRUE;
  $type_plugin->setConfiguration($configuration);
  $type_plugin->addTransition('preserve', 'Preserve', [
    'published',
    'archived',
  ], 'preserve');
  $workflow->save();
  $definition_update_manager = \Drupal::entityDefinitionUpdateManager();
  $field_definition = \Drupal::service('entity_field.manager')
    ->getFieldStorageDefinitions('node')['osu_a11y_remediation_email'];
  $definition_update_manager->installFieldStorageDefinition(
    'osu_a11y_remediation_email',
    'node',
    'osu_a11y_remediation',
    $field_definition,
  );

  $display_repository = \Drupal::service('entity_display.repository');
  $node_types = \Drupal::entityTypeManager()
    ->getStorage('node_type')
    ->loadMultiple();

  foreach ($node_types as $bundle => $node_type) {
    $display_repository->getFormDisplay('node', $bundle)
      ->setComponent('osu_a11y_remediation_email', [
        'type' => 'email_default',
        'weight' => 50,
      ])
      ->save();

    $display_repository->getViewDisplay('node', $bundle)
      ->removeComponent('osu_a11y_remediation_email')
      ->save();
  }
}
